### ISSUE TITLE
About MMD calculation

### ISSUE THREAD

**Issue by ghzhang233** [yolomeus/DMLab2020VFAE#1]
Thank you for sharing the code! I am wondering if *w_rand* and *b_rand* should be shared for calculating the MMD distance between *a* and *b*. I personally think that will make more sense.

https://github.com/yolomeus/DMLab2020VFAE/blob/e4499daba3cefb05b2c4e0d55c4ffba7a6be2796/losses.py#L100

**Comment by yolomeus** [comment]
Hi, thanks for pointing that out! 
Changed it real quick, think it looks correct now? If not, feel free to submit a pull request.

**Comment by ghzhang233** [comment]
Cool!
